version: 0.0
os: linux
files:
  - source: target/sample-spring-app-1.0-SNAPSHOT.jar
    destination: /tmp
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root